#! /bin/sh

# startup
pgrep -x sxhkd > /dev/null || sxhkd &
~/.local/bin/polylaunch.sh desaturated transparent &
feh --bg-fill ~/Pictures/.wallpaper/goku.jpg

# workspaces
bspc monitor -d I II III IV V VI VII VIII IX X # setup workspaces. You can change the roman numerals to arabic if you want

# wm settings
bspc config border_width         2 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a Emacs state=tiled
